package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/ComputationTime/finesse-api/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	var user model.User
	user.Email = input.Email
	user.Password = input.Password
	user.ID = "random  string"
	return "worked!", nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.Login) (string, error) {
	return "token", nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input *model.RefreshToken) (string, error) {
	return "token", nil
}

// Content is the resolver for the content field.
func (r *queryResolver) Content(ctx context.Context, num *int) ([]*model.Content, error) {
	var content_list []*model.Content

	dummy := model.Content{
		Source: "It works!",
		URL:    "www.google.com",
	}

	content_list = append(content_list, &dummy)
	return content_list, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
