// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ContentID int    `json:"content_id"`
	Source    string `json:"source"`
	URL       string `json:"url"`
}

type User struct {
	ID       int    `json:"_id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RefreshToken struct {
	Token string `json:"token"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewContent struct {
	Source string `json:"source"`
	URL    string `json:"url"`
}

type NewContentArray struct {
	Array []*NewContent `json:"array"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}




