// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID     string `json:"_id"`
	Source string `json:"source"`
	URL    string `json:"url"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RefreshToken struct {
	Token string `json:"token"`
}

type User struct {
	ID       string `json:"_id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
