// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ContentID string  `json:"content_id"`
	Source    string  `json:"source"`
	URL       string  `json:"url"`
	Views     int     `json:"views"`
	Likes     int     `json:"likes"`
	Score     float64 `json:"score"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewContent struct {
	Source string `json:"source"`
	URL    string `json:"url"`
}

type NewContentArray struct {
	Array []*NewContent `json:"array"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshToken struct {
	Token string `json:"token"`
}

type SeenContent struct {
	ContentID string `json:"content_id"`
	Liked     bool   `json:"liked"`
}

type User struct {
	UserID   int            `json:"user_id"`
	Username string         `json:"username"`
	Watched  []*SeenContent `json:"watched"`
}

type UserAuth struct {
	UserID   int    `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
